// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/pdcgo/san_collection/san_caches"
	"github.com/pdcgo/selling_service"
	"github.com/pdcgo/shared/configs"
	"github.com/pdcgo/shared/custom_connect"
	"github.com/urfave/cli/v3"
	"net/http"
)

// Injectors from wire.go:

func InitializeApp() (*cli.Command, error) {
	serveMux := http.NewServeMux()
	appConfig, err := configs.NewProductionConfig()
	if err != nil {
		return nil, err
	}
	db, err := NewDatabase(appConfig)
	if err != nil {
		return nil, err
	}
	cache, err := NewCache(appConfig)
	if err != nil {
		return nil, err
	}
	authorization := NewAuthorization(appConfig, db, cache)
	defaultInterceptor, err := custom_connect.NewDefaultInterceptor()
	if err != nil {
		return nil, err
	}
	client, err := NewFirestoreClient()
	if err != nil {
		return nil, err
	}
	sellingPushHandler := selling_service.NewSellingPushHandler(db)
	sellingPushHttpHandler := selling_service.NewSellingPushHttpHandler(sellingPushHandler)
	redisClient := NewRedisDatabase(appConfig)
	cacheManager := san_caches.NewRedisCacheManager(redisClient)
	registerHandler := selling_service.NewRegister(serveMux, db, authorization, defaultInterceptor, client, cache, sellingPushHttpHandler, cacheManager)
	registerReflectFunc := custom_connect.NewRegisterReflect(serveMux)
	serviceApiFunc := NewServiceApiFunc(serveMux, registerHandler, registerReflectFunc)
	command := NewApp(serviceApiFunc)
	return command, nil
}

// wire.go:

var environtment = wire.NewSet(
	NewCache,
	NewDatabase,
	NewFirestoreClient,
	NewRedisDatabase, san_caches.NewRedisCacheManager,
)
